### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by G-Harmon** [thayakawa-gh/SlackLogViewer#13]
There are no build instructions.
I would assume something like `cmake .` works, but it does not. It requires `cmake -DCMAKE_BUILD_TYPE=Debug .`

**Comment by G-Harmon** [comment]
It also did not build with gcc 9.4.0. I was getting errors with TBB:
```
/usr/include/c++/9/pstl/parallel_backend_tbb.h:70:10: error: ‘tbb::task’ has not been declared       
```
From https://community.intel.com/t5/Intel-oneAPI-Threading-Building/tbb-task-has-not-been-declared/m-p/1254418 , I guessed that gcc 9 and 10 do not work. with gcc 11 (11.1.0), it compiles.

**Comment by thayakawa-gh** [comment]
Hi @G-Harmon. Thank you for your report.

For GCC <= 10, the dependency on TBB has been removed and now it can be built with GCC 9.5.0.
TBB is used for fast sorting of retrieved messages by time. However, I don't think it would significantly affect the performance even without parallel STL algorithms.

In addition, I have added build instructions to the readme.
